### PR TITLE
performance: Change all over to using FromEvent rather than FromEventPattern

### PR DESCRIPTION
**Pull request by glennawatson**
- This has a performance boost of 3x
- The original research was done by @gluck
- This fixes issue #11

### CODE REVIEW

**Comment by glennawatson** [comment]
So based on @gluck test updated for System.Reactive 4.1.5.

``` ini

BenchmarkDotNet=v0.11.5, OS=Windows 10.0.18362
Intel Core i7-8550U CPU 1.80GHz (Kaby Lake R), 1 CPU, 8 logical and 4 physical cores
  [Host] : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3801.0
  Clr    : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.8.3801.0

Job=Clr  Runtime=Clr  

```
|           Method |     Mean |     Error |    StdDev |   Median |  Gen 0 |  Gen 1 | Gen 2 | Allocated |
|----------------- |---------:|----------:|----------:|---------:|-------:|-------:|------:|----------:|
| FromEventPattern | 6.867 us | 0.2595 us | 0.7103 us | 6.545 us | 0.3891 | 0.0610 |     - |   1.61 KB |
|        FromEvent | 2.211 us | 0.0757 us | 0.0708 us | 2.193 us | 0.3586 |      - |     - |   1.47 KB |

**Comment by worldbeater** [comment]
@glennawatson just to clarify, did you use the code from [the following gist](https://gist.github.com/gluck/da82c1b537e44b55daa8), or made some adjustments?

**Comment by glennawatson** [comment]
The code from the gist.

**Comment by glennawatson** [comment]
So my code produces now for example:

```cs
        /// <summary>
        /// Gets an observable which signals when the <see cref = "System.Windows.Interop.ComponentDispatcher.ThreadFilterMessage"/> event triggers.
        /// </summary>
        public static global::System.IObservable<(global::System.Windows.Interop.MSG&, global::System.Boolean&)> ComponentDispatcherThreadFilterMessage => global::System.Reactive.Linq.Observable.FromEvent<global::System.Windows.Interop.ThreadMessageEventHandler, (global::System.Windows.Interop.MSG&, global::System.Boolean&)>(eventHandler =>
        {
            void Handler(global::System.Windows.Interop.MSG msg, bool handled) => eventHandler((msg, handled));
            return Handler;
        }, x => global::System.Windows.Interop.ComponentDispatcher.ThreadFilterMessage += x, x => global::System.Windows.Interop.ComponentDispatcher.ThreadFilterMessage -= x);
```

So it just uses the local function feature, which I tested with a benchmark and has identical performance.

**Pull request merged**
