### PR TITLE
fix: Update README.md with an example

### PR DESCRIPTION
**Pull request by weitzhandler**
**What kind of change does this PR introduce?**
docs update

Includes a short introductory an example that demonstrates what Pharmacist actually does.

### CODE REVIEW

**Comment by RLittlesII** [comment]
Looking at this I am not sure it is accurate.

Pharmacist doesn't wrap individual INPC instances and provide events.  Rather Pharmacist looks at a given Package, Identifies all Events/Handlers and provides and `Observable.FromEvent` around them which you can access using the`Events()` method.

I am concerned that this addition will be more confusing to consumers.

**Comment by glennawatson** [comment]
I'll close this one and will implement some documentation about what it generates for.

**Comment by weitzhandler** [comment]
I can clarify it, but it's important consumers see HOW pharmacist actually works in field. The readme only tell you how to set it up, and what it theoretically does, it doesn't show how it's done and how to use it.

**Comment by glennawatson** [comment]
What your clarifying is plain incorrect though.

**Comment by glennawatson** [comment]
Well, not necessarily incorrect, but a bit misleading, and also incomplete.

**Comment by weitzhandler** [comment]
Great, thanks guys!

**Pull request closed without merging**
